Repository askap-vast/vast-pipeline, pull requests merged in 2021-06, with the labels that each got.

#546 Unused imports #545
  .github/workflows/lint.yml
  vast_pipeline/management/commands/clearpiperun.py
  vast_pipeline/management/commands/createmeasarrow.py
  vast_pipeline/management/commands/debugrun.py
  vast_pipeline/management/commands/initpiperun.py
  vast_pipeline/management/commands/restorepiperun.py
  vast_pipeline/models.py
  vast_pipeline/pipeline/association.py
  vast_pipeline/pipeline/forced_extraction.py
  vast_pipeline/pipeline/new_sources.py
  vast_pipeline/pipeline/utils.py
  vast_pipeline/tests/test_pipeline/test_association.py
  vast_pipeline/tests/test_regression/compare_runs.py
  vast_pipeline/tests/test_regression/test_epoch.py
  vast_pipeline/tests/test_regression/test_epoch_forced.py
  vast_pipeline/tests/test_regression/test_epoch_parallel_add_image.py
  vast_pipeline/tests/test_regression/test_forced.py
  vast_pipeline/tests/test_regression/test_normal.py
  vast_pipeline/tests/test_regression/test_parallel.py
  vast_pipeline/tests/test_regression/test_parallel_add_image.py
  vast_pipeline/tests/test_webserver.py
  vast_pipeline/utils/auth.py
  vast_pipeline/utils/view.py
  vast_pipeline/views.py
Labels: cleanup

#551 added processing spinner to source query table
  CHANGELOG.md
  static/js/datatables-pipeline.js
Labels: UI, enhancement, javascript

#559 added HOME_DATA_ROOT setting
  CHANGELOG.md
  docs/gettingstarted/configuration.md
  vast_pipeline/views.py
  webinterface/.env.template
  webinterface/settings.py
Labels: enhancement

#557 Add TNS external search for sources
  CHANGELOG.md
  docs/exploringwebsite/sourcepages.md
  docs/gettingstarted/configuration.md
  mkdocs.yml
  static/js/datatables-pipeline.js
  templates/source_detail.html
  vast_pipeline/serializers.py
  vast_pipeline/tests/test_external_query.py
  vast_pipeline/utils/external_query.py
  vast_pipeline/views.py
  webinterface/.env.template
  webinterface/settings.py
Labels: enhancement

#544 Separate image ingestion from main pipeline run
  CHANGELOG.md
  docs/adminusage/cli.md
  docs/adminusage/ingestimages.md
  mkdocs.yml
  templates/generic_table.html
  vast_pipeline/config_template.yaml.j2
  vast_pipeline/image/main.py
  vast_pipeline/ingest_config_template.yaml.j2
  vast_pipeline/management/commands/ingestimages.py
  vast_pipeline/management/commands/initingest.py
  vast_pipeline/pipeline/config.py
  vast_pipeline/pipeline/loading.py
  vast_pipeline/pipeline/main.py
  vast_pipeline/pipeline/utils.py
Labels: enhancement
