Repository askap-vast/vast-pipeline, pull requests merged in 2022-03, with the labels that each got.

#642 Fix empty groups in parallel association
  CHANGELOG.md
  vast_pipeline/pipeline/association.py
Labels: bug

#643 Addressed pandas DataFrame.append deprecation
  CHANGELOG.md
  vast_pipeline/pipeline/association.py
  vast_pipeline/pipeline/finalise.py
  vast_pipeline/pipeline/forced_extraction.py
  vast_pipeline/pipeline/utils.py
Labels: cleanup

#641 Drop Python 3.7 and dependency refresh
  .github/workflows/ci-docs-dev.yml
  .github/workflows/ci-docs-release.yml
  .github/workflows/test-suite.yml
  CHANGELOG.md
  README.md
  docs/architecture/intro.md
  poetry.lock
  pyproject.toml
  vast_pipeline/utils/utils.py
Labels: dependencies

#638 Support defer loading of dataTables data
  CHANGELOG.md
  static/js/datatables-pipeline.js
  vast_pipeline/views.py
Labels: enhancement, UI

#644 Fix astroquery Ned import deprecation
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  vast_pipeline/utils/external_query.py
Labels: python
