Repository askap-vast/vast-pipeline, pull requests merged in 2022-02, with the labels that each got.

#597 Update detail page titles
  CHANGELOG.md
  gulpfile.js
  templates/base.html
  templates/image_detail.html
  templates/measurement_detail.html
  templates/run_detail.html
  templates/source_detail.html
Labels: bug, UI

#614 Refactored add to favourites button to avoid refresh
  CHANGELOG.md
  docs/exploringwebsite/sourceanalysis.md
  static/js/source-fav.js
  static/js/toasts.js
  templates/base.html
  templates/messages.html
  templates/source_detail.html
  templates/source_fav_button.html
  templates/source_fav_modal.html
  templates/sources_etav_plot.html
  templates/sources_etav_plot_update.html
  vast_pipeline/views.py
Labels: enhancement, UI, python, javascript

#622 Updated Aladin VAST surveys
  CHANGELOG.md
  static/js/aladin-script.js
Labels: enhancement, UI

#620 Non-breaking npm audit fix update
  CHANGELOG.md
  package-lock.json
Labels: dependencies, javascript

#625 Pair metrics hover tooltip
  CHANGELOG.md
  docs/exploringwebsite/sourcedetail.md
  templates/source_detail.html
  vast_pipeline/plots.py
Labels: enhancement

#618 Produce IAU compliant source names
  CHANGELOG.md
  vast_pipeline/migrations/0010_update_source_names_iau_compliant.py
  vast_pipeline/pipeline/model_generator.py
  vast_pipeline/tests/test_coord_strings.py
  vast_pipeline/utils/utils.py
Labels: bug

#626 Add a ZTF cone search link
  CHANGELOG.md
  docs/exploringwebsite/sourcedetail.md
  docs/img/source-detail1.png
  docs/img/source-detail2.png
  docs/img/source-detail3.png
  docs/img/source-detail4.png
  templates/source_detail.html
Labels: enhancement

#634 bump jinja2 to v3
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: dependencies

#632 skip empty groups in new sources groupby-apply
  CHANGELOG.md
  vast_pipeline/pipeline/new_sources.py
Labels: bug, python

#633 URI encode NED object names
  CHANGELOG.md
  static/js/datatables-pipeline.js
Labels: javascript
