Repository askap-vast/vast-pipeline, pull requests merged in 2025-01, with the labels that each got.

#759 752 merge sky region
  CHANGELOG.md
  vast_pipeline/models.py
  vast_pipeline/pipeline/utils.py
Labels: v2.0 experiment, do not merge

#798 Update dependencies
  .github/workflows/test-suite.yml
  CHANGELOG.md
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  vast_pipeline/_version.py
  vast_pipeline/pipeline/loading.py
  vast_pipeline/pipeline/utils.py
  vast_pipeline/plots.py
  vast_pipeline/utils/external_query.py
  vast_pipeline/utils/utils.py
  webinterface/settings.py
Labels: dependencies, v2.0

#800 Update the measurements creation to use parquet/dask rather than arrow/vaex files
  docs/adminusage/cli.md
  docs/exploringwebsite/runpages.md
  docs/img/action-buttons.png
  docs/img/arrow-files-available.png
  docs/img/docs-example-run-detail.png
  docs/img/generate-arrow-button.png
  docs/img/generate-arrow-files-log.png
  docs/img/generate-arrow-modal.png
  docs/img/generate-arrow-notification.png
  docs/img/generate-measurements-parquet-log.png
  docs/img/generate-parquet-button.png
  docs/img/generate-parquet-modal.png
  docs/img/generate-parquet-notification.png
  docs/img/measurements-parquet-available.png
  docs/img/run-detail1.png
  docs/img/run-detail2.png
  docs/img/run-detail3.png
  docs/img/run-detail6.png
  docs/img/run-detail7.png
  docs/img/run-detail9.png
  docs/outputs/outputs.md
  docs/outputs/usingoutputs.md
  docs/using/genarrow.md
  docs/using/genparquet.md
  docs/using/runconfig.md
  poetry.lock
  pyproject.toml
  static/js/run-detail.js
  templates/generic_table.html
  templates/run_detail.html
  vast_pipeline/config_template.yaml.j2
  vast_pipeline/forms.py
  vast_pipeline/management/commands/clearpiperun.py
  vast_pipeline/management/commands/createmeasparquet.py
  vast_pipeline/management/commands/runpipeline.py
  vast_pipeline/pipeline/config.py
  vast_pipeline/pipeline/utils.py
  vast_pipeline/utils/utils.py
  vast_pipeline/views.py
  webinterface/settings.py
Labels: v2.0

#714 Correctly calculate new_high_sigma
  CHANGELOG.md
  vast_pipeline/pipeline/new_sources.py
  vast_pipeline/tests/test_regression/test_epoch.py
  vast_pipeline/tests/test_regression/test_epoch_parallel_add_image.py
  vast_pipeline/tests/test_regression/test_normal.py
Labels: do not merge, v2.0

#801 Update docs dependencies
  CHANGELOG.md
  docs/adminusage/cli.md
  docs/exploringwebsite/measurementdetail.md
  docs/exploringwebsite/sourceanalysis.md
  docs/gettingstarted/configuration.md
  docs/outputs/outputs.md
  docs/using/access.md
  docs/using/genparquet.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  vast_pipeline/image/utils.py
  vast_pipeline/management/commands/clearpiperun.py
  vast_pipeline/management/commands/createmeasparquet.py
  vast_pipeline/management/commands/debugrun.py
  vast_pipeline/management/commands/ingestimages.py
  vast_pipeline/management/commands/initingest.py
  vast_pipeline/management/commands/initpiperun.py
  vast_pipeline/management/commands/restorepiperun.py
  vast_pipeline/management/commands/runpipeline.py
  vast_pipeline/pipeline/config.py
  vast_pipeline/pipeline/utils.py
  vast_pipeline/utils/auth.py
  vast_pipeline/utils/utils.py
Labels: do not merge, v2.0

#792 Fix the error_ellipse calculation.
  CHANGELOG.md
  vast_pipeline/image/main.py
  vast_pipeline/tests/test_regression/test_epoch.py
  vast_pipeline/tests/test_regression/test_epoch_forced.py
  vast_pipeline/tests/test_regression/test_epoch_parallel_add_image.py
  vast_pipeline/tests/test_regression/test_normal.py
Labels: bug, do not merge, v2.0
